# Use the official Python image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the Flask app code into the container
COPY . /app

# Install dependencies
RUN pip install -r requirements.txt

# Expose the port that Flask will run on
EXPOSE 5002

# Command to run the Flask app
CMD ["python", "app.py"]
